### ISSUE TITLE
CPU List and Meter Refactoring

### ISSUE THREAD

**Issue by srowhani** [proccoli/proccoli-pm#17]
- CPUList
  - Headers don't need to update.
    - Waste to rewrite the labels every time there's an update `e.g (cpu0,cpu1...)
    - Update method in CPUList should only have to update the meters after initialization.
- CPUMeter
  - Should be a ProgressBar, not a ListWalker
        - CPUList should handle the instances.
        - You can have ListWalker instance in CPUMeter.
  - Can't sleep thread, that will block the whole program.
      - Instead to gather delta, store previous stat.
      - In the update method of a meter, you can pass the stat file in.
      - Compute it once in the context of the CPUList's update method, and update the meters with that value. No reason to dupe this calculation.

**Comment by SSlatter** [comment]
Aight I'll fix er up
